# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/IPC:IpcLib"],
)

cc_binary(
    name = "send_main",
    srcs = ["send_main.cc"],
    deps = ["//src/IPC:IpcLib"],
)